### ISSUE TITLE
Is there a way to have entity collections stored in the same model as single entity data?

### ISSUE THREAD

**Issue by bt-frog** [outlandishideas/kasia#21]
I have a custom content type of `work`. I want the data returned by calling either `connectWpPost('work')(WorkComponent)` or `connectWpPost('work', '')(WorkComponent)` to store the entities in the same property of the work model. **Note:** I admit it's a small hack to retrieve a collection of entities by passing an empty string ID to the API; if there's a better way please advise.

When the data is being processed/normalized, I can see why the collection is not being assigned to the `work` model. In `connectWpPost.js` starting at line 161 you have:
```
return {
  kasia: _defineProperty({
    query: query
  }, name, findEntity(entityCollection, entityId))
};

// Since I'm passing an empty `entityId`, the result is null as designed.
```
Is there a way to have the result of the call always return a collection of entities?

**Comment by sdgluck** [comment]
Might [`@connectWpQuery`](https://github.com/outlandishideas/kasia#connectwpqueryqueryfn-propscomparatorfn--component) accomplish what you're after?

**Comment by bt-frog** [comment]
Hi @sdgluck. Thanks for the suggestion. I'll give that a quick go and update this comment with result.
