### ISSUE TITLE
Expose action creators to fetch posts and run arbitrary queries outside decorators

### ISSUE THREAD

**Issue by sdgluck** [outlandishideas/kasia#3]
Exposing action creators would allow the developer to dispatch requests for data from WordPress without having to declare that data as attached to a component using the included decorators, and also have it stored implicitly under the `wordpress` namespace in the store.

It would look something like:

``` js
import { fetchPost, fetchQuery } from 'kasia/creators'

store.dispatch(fetchPost(Page, 'page-slug'))
store.dispatch(fetchQuery((wpapi) => wpapi.news().embed().get()))
```

Probably best to pull out the query reconciliation stuff from the HOCs and share it between the various data fetching pathways.

Another thing to consider is actions whose response from the API are not normalised and placed on the store. For example, actions for creating and modifying posts:

``` js
import { createPost, modifyPost } from 'kasia/creators'

store.dispatch(createPost(post))
store.dispatch(modifyPost(id, post))
```

**Comment by nickpalmer** [comment]
I enhance my store with actions so returning them from the `kasia({ wpapi })` call made the most sense to me. Not opposed to having them exposed elsewhere.

See here: https://github.com/outlandishideas/kasia/pull/70

**Comment by sdgluck** [comment]
Thanks @nickpalmer! I have published that onto `beta`.
