### ISSUE TITLE
TypeError: inherit is not a function

### ISSUE THREAD

**Issue by luandro** [outlandishideas/kasia#32]
This seems to actually be a problem with `wpapi`, but since I'm using because of `Kasia` I might as well ask it here.

I'm importing both according to docs:

```
import Kasia from 'kasia';
import wpapi from 'wpapi';

const WP = new wpapi({ endpoint: 'http://wordpress.com/wp-json' });
```

But when running I get:

```
Uncaught endpoint-request.js?c4d6:29
TypeError: inherit is not a function
```

Any thoughts?

**Comment by sdgluck** [comment]
I suspect this is a problem with the bundler again? Please share you webpack configuration.

**Comment by luandro** [comment]
It's exactly the same as [react-boilerplate](https://github.com/mxstbr/react-boilerplate), and [this](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js) is the relevant Webpack config file.

**Comment by sdgluck** [comment]
I'm closing this as I suspect this it isn't a problem with Kasia, but with your Webpack configuration. Unfortunately I don't have the time to look into this. If you found a solution please share.
