### ISSUE TITLE
Prefetching solution?

### ISSUE THREAD

**Issue by sdgluck** [outlandishideas/kasia#39]
Being able to start a query on behalf of an as yet unmounted connected component, which the component can then hook into instead of starting its own would be nice. For example, when the user hovers on a link to a Post the query can start before the component is mounted.

Food for thought...

**Comment by nickpalmer** [comment]
This can be done with an intermediate component. You put the query on the intermediate component and then it doesn't render its children until the query is complete, passing on the connectWpQuery results as props.

It can also rendering a loading spinner or any error. Kasia could provide that kind of component but it is almost trivial to do yourself so I wonder if it would end up being too opinionated to have real value. Maybe with generic callbacks for the various states?

**Comment by sdgluck** [comment]
I think you're right that this would be too opinionated @nickpalmer. Thanks for your feedback!
