### ISSUE TITLE
Allow content type definition to be passed straight to decorator

### ISSUE THREAD

**Issue by sdgluck** [outlandishideas/kasia#41]
Save having to register a custom type that is used in only one place.

Something like this...

```
@connectWpPost({ name: 'book', plural: 'books' }, (props) => props.params.id)
class Book extends React.Component {
  ...
}
```

Maybe we could even derive a custom type from a string, e.g. `'book'` and append the `'s'` for the plural and call it a day.

```
@connectWpPost('book', (props) => props.params.id)
class Book extends React.Component {
  ...
}
```

**Comment by kadamwhite** [comment]
I'd caution against blindly applying "s", pluralization's too irregular and that would make it harder to support resources named in other languages. This doesn't mean the reduced signature couldn't be supported, necessarily, just that it's probably better to allow both to be passed in if needed and only do the `string + 's'` inference if the plural isn't provided.

**Comment by sdgluck** [comment]
@kadamwhite Thanks very much for your input! 👍 Yes I was thinking that both signatures could be supported, object or string, with a warning that naive pluralisation (`string + 's'`) would be employed should the consumer decide to use the latter, more simple form. However it did occur to me after posting this that it may be taking the whole "convenience" thing too far.

**Comment by sdgluck** [comment]
Closing as on second thought I think this isn't that useful of a feature.
