### ISSUE TITLE
Testing apps that use kasia?

### ISSUE THREAD

**Issue by nickpalmer** [outlandishideas/kasia#58]
There are two great advantages I see to redux-saga:

1) Complex series of operations are easy to express. One can yield a first call and then use that data in a second call without having to resort to chaining promises. The order of operations is clear and the data dependencies are directly visible in the code.

2) They are easy to test. I can easily write a test that ensures the the right API calls are made in the right order with the right data.

With kasia how do you express complex multi call operations without a promise chain?
With kasia, how do you test that a component is making the calls it should be making when it is mounted?

Ideas on how best to address these areas appreciated. I am happy to update the documentation with whatever discussion occurs here.

**Comment by sdgluck** [comment]
Hey Nick-

> With kasia how do you express complex multi call operations without a promise chain?

Currently Kasia does not support generators as query functions so unless async/await is available to you the usual Promise approach is the only way. If support for generators is desirable I can look into implementing this.

> With kasia, how do you test that a component is making the calls it should be making when it is mounted?

With regards to testing Kasia components, this can be done by 1) making your component available as a named export prior to decoration and then 2) lifting the query function from the `connectWpQuery` decorator and exporting that as a named export also.

So something like this:

```js
export function postQuery (wpapi) {...}

export class Post extends Component {...}

@connectWpQuery(postQuery, (thisProps, nextProps) => thisProps.id !== nextProps.id)
export default Post
```

You can now import and test the component and its query function independently of each other. I hope that helps?

**Comment by nickpalmer** [comment]
Yeah, I was thinking that using generators as query functions would be much cleaner. Since the library is already using sagas it would seem to make sense to allow complex queries to be expressed using sagas as well instead of forcing users to go back to promises or async/await. I am open to looking to contribute this, but would want input about API issues for it. Does the API do generator detection, set a global flag forcing all generator usage, or add an options parameter to query construction?

The latter testing approach looks like what I would expect even with generator based queries, I just wanted to make sure this was what you were thinking. I will do a PR to update the docs with this.

**Comment by nickpalmer** [comment]
I got generator support working by changing wrapQueryFn in `connect.js` to return a generator which uses call:

```
 export function wrapQueryFn (queryFn, props, state) {
   return function* (wpapi) {
    yield call(queryFn, wpapi, props, state);
   }
}
```

In theory, detecting if queryFn is a generator and doing one or the other should add transparent support for generators as query function.

Alternatively, a flag indicating all queries will be done with generators would also work.

**Comment by nickpalmer** [comment]
It turns out the change to support generators is completely transparent and totally backwards compatible, making all the query functions easy to test like sagas are. Loving it!

**Comment by nickpalmer** [comment]
Closing this since all changes have been merged. Thanks for being awesome at accepting PRs!

**Comment by joshlevinson** [comment]
@nickpalmer Do you have any examples of your use of generators in query functions? V. interested, as I'm only just learning generators.

**Comment by nickpalmer** [comment]
```javascript
export function getTagsBySlug(wpapi, slug) {
  return wpapi.tags().slug(slug).get();
}
export function getPostsByTagId(wpapi, id) {
  return wpapi.posts().embed().tag(id).get();
}
export function* doFetchPostsByTopicSlug(wpapi, slug) {
  let stories = [];
  const tag = yield call(getTagsBySlug, wpapi, slug);
  if (tag.length) {
    stories = yield call(getPostsByTagId, wpapi, tag[0].id);
  }
  return stories;
}
```

To test you simply import these three functions into your test and:
- Mock `wpapi` using `jest.fn` and test `getTagsBySlug` and `getPostsByTagId`.
- Test `doFetchPostsByTopicSlug` like any other generator.
