### ISSUE TITLE
React PropTypes warning

### ISSUE THREAD

**Issue by nickpalmer** [outlandishideas/kasia#61]
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

**Comment by sdgluck** [comment]
I've noticed this too but always forget to file an issue- so thank you!

Looks like the only place we are using `PropTypes` is in [`connect.js#L55`](https://github.com/outlandishideas/kasia/blob/b7dd36df2942ce94d4f96c4ab85611b35ed473e8/src/connect.js#L55).
